package im

import (
	"context"
	"fmt"
	"strings"

	"github.com/RapidAI/CodeClaw/hub/internal/nlrouter"
)

// ---------------------------------------------------------------------------
// Dependency interfaces — abstract external services to avoid circular imports
// ---------------------------------------------------------------------------

// SessionManager abstracts the Remote_Session_Manager.
type SessionManager interface {
	CreateSession(ctx context.Context, userID, tool, projectPath, prompt string) (sessionID string, err error)
	WriteInput(ctx context.Context, sessionID, text string) error
	ListSessions(ctx context.Context, userID string) ([]SessionInfo, error)
	GetSession(ctx context.Context, sessionID string) (*SessionInfo, error)
	InterruptSession(ctx context.Context, sessionID string) error
	KillSession(ctx context.Context, sessionID string) error
}

// DeviceManager abstracts the DeviceLister.
type DeviceManager interface {
	ListMachines(ctx context.Context, userID string) ([]MachineInfo, error)
	SendToMachine(machineID string, msg any) error
	IsMachineOnline(machineID string) bool
}

// ScreenshotService abstracts screenshot functionality.
type ScreenshotService interface {
	RequestScreenshot(ctx context.Context, sessionID string) (imageKey string, err error)
}

// MCPRegistry abstracts the MCP registry for tool invocation.
type MCPRegistry interface {
	CallTool(ctx context.Context, serverID, toolName string, input map[string]interface{}) (interface{}, error)
	ListServers(ctx context.Context) []MCPServerInfo
}

// SkillExecutor abstracts the Skill executor.
type SkillExecutor interface {
	Execute(ctx context.Context, skillName string, params map[string]interface{}, progressFn func(step int, msg string)) error
	List(ctx context.Context) []SkillInfo
}

// SkillCrystallizer abstracts the Skill crystallizer.
type SkillCrystallizer interface {
	CrystallizeFromContext(ctx context.Context, userID string) (*SkillCandidate, error)
}

// MemoryStoreOps abstracts the Memory_Store for view/clear operations.
type MemoryStoreOps interface {
	Get(ctx context.Context, userID string) (*MemoryData, error)
	Clear(ctx context.Context, userID string) error
	RecordAction(ctx context.Context, userID string, entry MemoryEntry) error
}

// ContextManager abstracts the Context_Window manager.
type ContextManager interface {
	Get(userID string) *ContextWindowData
}

// ToolCatalogChecker abstracts the Tool_Catalog for availability checks.
type ToolCatalogChecker interface {
	IsToolAvailable(toolName string) bool
	ListAvailableTools() []string
}

// ---------------------------------------------------------------------------
// Lightweight info structs used by the executor interfaces
// ---------------------------------------------------------------------------

// SessionInfo holds minimal session metadata.
type SessionInfo struct {
	ID     string
	Tool   string
	Title  string
	Status string
}

// MachineInfo holds minimal machine metadata.
type MachineInfo struct {
	ID       string
	Name     string
	Platform string
	Online   bool
}

// MCPServerInfo holds minimal MCP server metadata for listing.
type MCPServerInfo struct {
	ID           string
	Name         string
	HealthStatus string
	Tools        []MCPToolInfo
}

// MCPToolInfo holds minimal MCP tool metadata.
type MCPToolInfo struct {
	Name        string
	Description string
}

// SkillInfo holds minimal skill metadata for listing.
type SkillInfo struct {
	Name        string
	Description string
	Triggers    []string
	Status      string
}

// SkillCandidate holds a candidate skill generated by the crystallizer.
type SkillCandidate struct {
	Name        string
	Description string
	Steps       []string
}

// MemoryData holds user memory data for display.
type MemoryData struct {
	DefaultTool   string
	Preferences   map[string]string
	RecentCount   int
	PatternCounts map[string]int
}

// MemoryEntry represents a single recorded action for the memory store.
type MemoryEntry struct {
	Intent string
	Params map[string]interface{}
}

// ContextWindowData holds context window state for session resolution.
type ContextWindowData struct {
	ActiveSession string
	ActiveTool    string
}

// ---------------------------------------------------------------------------
// BridgeExecutor — implements IntentExecutor
// ---------------------------------------------------------------------------

// BridgeExecutor maps parsed intents to concrete operations by delegating
// to the appropriate service interface. All results are wrapped in
// GenericResponse with Chinese messages and English technical terms preserved.
type BridgeExecutor struct {
	sessions     SessionManager
	devices      DeviceManager
	screenshots  ScreenshotService
	mcpRegistry  MCPRegistry
	skillExec    SkillExecutor
	crystallizer SkillCrystallizer
	memoryStore  MemoryStoreOps
	contextMgr   ContextManager
	toolCatalog  ToolCatalogChecker
}

// NewBridgeExecutor creates a BridgeExecutor with all dependencies.
func NewBridgeExecutor(
	sessions SessionManager,
	devices DeviceManager,
	screenshots ScreenshotService,
	mcpRegistry MCPRegistry,
	skillExec SkillExecutor,
	crystallizer SkillCrystallizer,
	memoryStore MemoryStoreOps,
	contextMgr ContextManager,
	toolCatalog ToolCatalogChecker,
) *BridgeExecutor {
	return &BridgeExecutor{
		sessions:     sessions,
		devices:      devices,
		screenshots:  screenshots,
		mcpRegistry:  mcpRegistry,
		skillExec:    skillExec,
		crystallizer: crystallizer,
		memoryStore:  memoryStore,
		contextMgr:   contextMgr,
		toolCatalog:  toolCatalog,
	}
}

// Execute dispatches an intent to the appropriate handler and returns a
// GenericResponse. This is the main entry point implementing IntentExecutor.
func (b *BridgeExecutor) Execute(ctx context.Context, userID string, intent *nlrouter.Intent) (*GenericResponse, error) {
	switch intent.Name {
	case nlrouter.IntentLaunchSession:
		return b.handleLaunchSession(ctx, userID, intent)
	case nlrouter.IntentSendInput:
		return b.handleSendInput(ctx, userID, intent)
	case nlrouter.IntentListMachines:
		return b.handleListMachines(ctx, userID)
	case nlrouter.IntentListSessions:
		return b.handleListSessions(ctx, userID)
	case nlrouter.IntentSessionDetail:
		return b.handleSessionDetail(ctx, userID, intent)
	case nlrouter.IntentUseSession:
		return b.handleUseSession(ctx, userID, intent)
	case nlrouter.IntentExitSession:
		return b.handleExitSession(userID)
	case nlrouter.IntentInterruptSession:
		return b.handleInterruptSession(ctx, userID, intent)
	case nlrouter.IntentKillSession:
		return b.handleKillSession(ctx, userID, intent)
	case nlrouter.IntentScreenshot:
		return b.handleScreenshot(ctx, userID, intent)
	case nlrouter.IntentCallMCPTool:
		return b.handleCallMCPTool(ctx, intent)
	case nlrouter.IntentRunSkill:
		return b.handleRunSkill(ctx, intent)
	case nlrouter.IntentViewMemory:
		return b.handleViewMemory(ctx, userID)
	case nlrouter.IntentClearMemory:
		return b.handleClearMemory(ctx, userID)
	case nlrouter.IntentCrystallizeSkill:
		return b.handleCrystallizeSkill(ctx, userID)
	case nlrouter.IntentHelp:
		return b.handleHelp(), nil
	case nlrouter.IntentUnknown:
		return b.handleUnknown(intent), nil
	default:
		return b.handleUnknown(intent), nil
	}
}

// ---------------------------------------------------------------------------
// Intent handlers
// ---------------------------------------------------------------------------

// handleLaunchSession creates a new remote session via SessionManager.
// It validates tool availability through ToolCatalog first.
func (b *BridgeExecutor) handleLaunchSession(ctx context.Context, userID string, intent *nlrouter.Intent) (*GenericResponse, error) {
	tool := paramStr(intent.Params, "tool")
	projectPath := paramStr(intent.Params, "project_path")
	prompt := paramStr(intent.Params, "prompt")

	if tool == "" {
		return errorResponse(400, "缺少工具名称参数", "请指定要使用的工具，例如 \"用 Claude 启动会话\"。"), nil
	}

	// Validate tool availability.
	if b.toolCatalog != nil && !b.toolCatalog.IsToolAvailable(tool) {
		available := b.toolCatalog.ListAvailableTools()
		body := fmt.Sprintf("工具 \"%s\" 不可用或未安装。", tool)
		if len(available) > 0 {
			body += fmt.Sprintf("\n\n可用工具: %s", strings.Join(available, ", "))
		}
		return errorResponse(404, "工具不可用", body), nil
	}

	if b.sessions == nil {
		return errorResponse(500, "会话服务未配置", "Remote_Session_Manager 未初始化，请联系管理员。"), nil
	}

	sessionID, err := b.sessions.CreateSession(ctx, userID, tool, projectPath, prompt)
	if err != nil {
		return errorResponse(500, "创建会话失败", fmt.Sprintf("错误: %s\n建议: 请检查设备是否在线，或尝试其他工具。", err.Error())), nil
	}

	return &GenericResponse{
		StatusCode: 200,
		StatusIcon: "🚀",
		Title:      "会话已创建",
		Body:       fmt.Sprintf("已使用 %s 启动新会话。", tool),
		Fields: []ResponseField{
			{Label: "Session ID", Value: sessionID},
			{Label: "工具", Value: tool},
		},
		Actions: []ResponseAction{
			{Label: "切换到此会话", Command: fmt.Sprintf("/use %s", sessionID), Style: "primary"},
		},
	}, nil
}

// handleSendInput sends text to the active or specified session.
func (b *BridgeExecutor) handleSendInput(ctx context.Context, userID string, intent *nlrouter.Intent) (*GenericResponse, error) {
	text := paramStr(intent.Params, "text")
	if text == "" {
		return errorResponse(400, "缺少输入内容", "请提供要发送到会话的文本。"), nil
	}

	sessionID := b.resolveSessionID(ctx, userID, intent)
	if sessionID == "" {
		return errorResponse(400, "未指定目标会话", "请先使用 /use 切换到一个会话，或指定会话编号。"), nil
	}

	if b.sessions == nil {
		return errorResponse(500, "会话服务未配置", "Remote_Session_Manager 未初始化。"), nil
	}

	if err := b.sessions.WriteInput(ctx, sessionID, text); err != nil {
		return errorResponse(500, "发送失败", fmt.Sprintf("无法发送到会话 %s: %s\n建议: 请确认会话仍在运行。", sessionID, err.Error())), nil
	}

	return &GenericResponse{
		StatusCode: 200,
		StatusIcon: "✅",
		Title:      "已发送",
		Body:       fmt.Sprintf("已发送到会话 %s", sessionID),
	}, nil
}

// handleListMachines returns the user's device list.
func (b *BridgeExecutor) handleListMachines(ctx context.Context, userID string) (*GenericResponse, error) {
	if b.devices == nil {
		return errorResponse(500, "设备服务未配置", "DeviceManager 未初始化。"), nil
	}

	machines, err := b.devices.ListMachines(ctx, userID)
	if err != nil {
		return errorResponse(500, "获取设备列表失败", fmt.Sprintf("错误: %s", err.Error())), nil
	}

	if len(machines) == 0 {
		return &GenericResponse{
			StatusCode: 200,
			StatusIcon: "ℹ️",
			Title:      "设备列表",
			Body:       "暂无已注册的设备。",
		}, nil
	}

	fields := make([]ResponseField, 0, len(machines))
	for _, m := range machines {
		status := "🔴 离线"
		if m.Online {
			status = "🟢 在线"
		}
		name := m.Name
		if name == "" {
			name = m.ID
		}
		fields = append(fields, ResponseField{
			Label: name,
			Value: fmt.Sprintf("%s | %s | %s", m.Platform, status, m.ID),
		})
	}

	return &GenericResponse{
		StatusCode: 200,
		StatusIcon: "🖥",
		Title:      fmt.Sprintf("设备列表 (%d 台)", len(machines)),
		Fields:     fields,
		Actions: []ResponseAction{
			{Label: "查看会话", Command: "/sessions", Style: "default"},
		},
	}, nil
}

// handleListSessions returns the user's session list.
func (b *BridgeExecutor) handleListSessions(ctx context.Context, userID string) (*GenericResponse, error) {
	if b.sessions == nil {
		return errorResponse(500, "会话服务未配置", "SessionManager 未初始化。"), nil
	}

	sessions, err := b.sessions.ListSessions(ctx, userID)
	if err != nil {
		return errorResponse(500, "获取会话列表失败", fmt.Sprintf("错误: %s", err.Error())), nil
	}

	if len(sessions) == 0 {
		return &GenericResponse{
			StatusCode: 200,
			StatusIcon: "ℹ️",
			Title:      "会话列表",
			Body:       "暂无活跃会话。",
		}, nil
	}

	fields := make([]ResponseField, 0, len(sessions))
	for _, s := range sessions {
		fields = append(fields, ResponseField{
			Label: fmt.Sprintf("[%s] %s", s.ID, s.Tool),
			Value: fmt.Sprintf("%s | %s", s.Title, s.Status),
		})
	}

	return &GenericResponse{
		StatusCode: 200,
		StatusIcon: "📋",
		Title:      fmt.Sprintf("会话列表 (%d 个)", len(sessions)),
		Fields:     fields,
		Actions: []ResponseAction{
			{Label: "切换会话", Command: "/use <编号>", Style: "primary"},
		},
	}, nil
}

// handleSessionDetail returns details for a specific session.
func (b *BridgeExecutor) handleSessionDetail(ctx context.Context, userID string, intent *nlrouter.Intent) (*GenericResponse, error) {
	sessionID := b.resolveSessionID(ctx, userID, intent)
	if sessionID == "" {
		return errorResponse(400, "未指定会话", "请提供会话编号，例如 \"查看会话 1 的详情\"。"), nil
	}

	if b.sessions == nil {
		return errorResponse(500, "会话服务未配置", "SessionManager 未初始化。"), nil
	}

	info, err := b.sessions.GetSession(ctx, sessionID)
	if err != nil {
		return errorResponse(404, "会话未找到", fmt.Sprintf("无法获取会话 %s: %s", sessionID, err.Error())), nil
	}

	return &GenericResponse{
		StatusCode: 200,
		StatusIcon: "📊",
		Title:      "会话详情",
		Fields: []ResponseField{
			{Label: "Session ID", Value: info.ID},
			{Label: "工具", Value: info.Tool},
			{Label: "标题", Value: info.Title},
			{Label: "状态", Value: info.Status},
		},
		Actions: []ResponseAction{
			{Label: "切换到此会话", Command: fmt.Sprintf("/use %s", info.ID), Style: "primary"},
			{Label: "截屏", Command: fmt.Sprintf("/screenshot %s", info.ID), Style: "default"},
		},
	}, nil
}

// handleUseSession sets the active session in the context window.
func (b *BridgeExecutor) handleUseSession(ctx context.Context, userID string, intent *nlrouter.Intent) (*GenericResponse, error) {
	sessionID := b.resolveSessionID(ctx, userID, intent)
	if sessionID == "" {
		return errorResponse(400, "未指定会话", "请提供会话编号，例如 \"切换到会话 1\"。"), nil
	}

	// Verify session exists.
	if b.sessions != nil {
		info, err := b.sessions.GetSession(ctx, sessionID)
		if err != nil {
			return errorResponse(404, "会话未找到", fmt.Sprintf("无法找到会话 %s: %s\n建议: 使用 /sessions 查看可用会话。", sessionID, err.Error())), nil
		}
		// Update context window with session info.
		if b.contextMgr != nil {
			cw := b.contextMgr.Get(userID)
			cw.ActiveSession = info.ID
			cw.ActiveTool = info.Tool
		}
		return &GenericResponse{
			StatusCode: 200,
			StatusIcon: "✅",
			Title:      "已切换会话",
			Body:       fmt.Sprintf("已切换到会话: %s [%s]\n\n现在直接发文本就是给这个会话发命令。\n发送 \"退出会话\" 或 /exit 退出上下文。", info.Title, info.Tool),
			Fields: []ResponseField{
				{Label: "Session ID", Value: info.ID},
				{Label: "工具", Value: info.Tool},
			},
		}, nil
	}

	// Fallback if session manager is nil — just set context.
	if b.contextMgr != nil {
		cw := b.contextMgr.Get(userID)
		cw.ActiveSession = sessionID
	}

	return &GenericResponse{
		StatusCode: 200,
		StatusIcon: "✅",
		Title:      "已切换会话",
		Body:       fmt.Sprintf("已切换到会话 %s。直接发文本即为命令。", sessionID),
	}, nil
}

// handleExitSession clears the active session from the context window.
func (b *BridgeExecutor) handleExitSession(userID string) (*GenericResponse, error) {
	if b.contextMgr != nil {
		cw := b.contextMgr.Get(userID)
		old := cw.ActiveSession
		cw.ActiveSession = ""
		cw.ActiveTool = ""
		if old == "" {
			return &GenericResponse{
				StatusCode: 200,
				StatusIcon: "ℹ️",
				Title:      "无活跃会话",
				Body:       "当前没有活跃的会话上下文。",
			}, nil
		}
		return &GenericResponse{
			StatusCode: 200,
			StatusIcon: "✅",
			Title:      "已退出会话",
			Body:       fmt.Sprintf("已退出会话 %s 的上下文。", old),
		}, nil
	}

	return &GenericResponse{
		StatusCode: 200,
		StatusIcon: "✅",
		Title:      "已退出会话",
		Body:       "已退出当前会话上下文。",
	}, nil
}

// handleInterruptSession sends an interrupt signal to a session.
func (b *BridgeExecutor) handleInterruptSession(ctx context.Context, userID string, intent *nlrouter.Intent) (*GenericResponse, error) {
	sessionID := b.resolveSessionID(ctx, userID, intent)
	if sessionID == "" {
		return errorResponse(400, "未指定会话", "请提供会话编号。"), nil
	}

	if b.sessions == nil {
		return errorResponse(500, "会话服务未配置", "SessionManager 未初始化。"), nil
	}

	if err := b.sessions.InterruptSession(ctx, sessionID); err != nil {
		return errorResponse(500, "中断失败", fmt.Sprintf("无法中断会话 %s: %s", sessionID, err.Error())), nil
	}

	return &GenericResponse{
		StatusCode: 200,
		StatusIcon: "⏸",
		Title:      "已发送中断信号",
		Body:       fmt.Sprintf("已向会话 %s 发送中断信号。", sessionID),
	}, nil
}

// handleKillSession sends a kill signal to a session.
func (b *BridgeExecutor) handleKillSession(ctx context.Context, userID string, intent *nlrouter.Intent) (*GenericResponse, error) {
	sessionID := b.resolveSessionID(ctx, userID, intent)
	if sessionID == "" {
		return errorResponse(400, "未指定会话", "请提供会话编号。"), nil
	}

	if b.sessions == nil {
		return errorResponse(500, "会话服务未配置", "SessionManager 未初始化。"), nil
	}

	if err := b.sessions.KillSession(ctx, sessionID); err != nil {
		return errorResponse(500, "终止失败", fmt.Sprintf("无法终止会话 %s: %s", sessionID, err.Error())), nil
	}

	// Clear active session if it was the killed one.
	if b.contextMgr != nil {
		cw := b.contextMgr.Get(userID)
		if cw.ActiveSession == sessionID {
			cw.ActiveSession = ""
			cw.ActiveTool = ""
		}
	}

	return &GenericResponse{
		StatusCode: 200,
		StatusIcon: "⏹",
		Title:      "已发送终止信号",
		Body:       fmt.Sprintf("已向会话 %s 发送终止信号。", sessionID),
	}, nil
}

// handleScreenshot requests a screenshot from a session.
func (b *BridgeExecutor) handleScreenshot(ctx context.Context, userID string, intent *nlrouter.Intent) (*GenericResponse, error) {
	sessionID := b.resolveSessionID(ctx, userID, intent)
	if sessionID == "" {
		return errorResponse(400, "未指定会话", "请提供会话编号。"), nil
	}

	if b.screenshots == nil {
		return errorResponse(500, "截屏服务未配置", "ScreenshotService 未初始化。"), nil
	}

	imageKey, err := b.screenshots.RequestScreenshot(ctx, sessionID)
	if err != nil {
		return errorResponse(500, "截屏失败", fmt.Sprintf("无法获取会话 %s 的截屏: %s", sessionID, err.Error())), nil
	}

	return &GenericResponse{
		StatusCode: 200,
		StatusIcon: "📸",
		Title:      "截屏完成",
		Body:       fmt.Sprintf("已获取会话 %s 的截屏。", sessionID),
		Fields: []ResponseField{
			{Label: "Image Key", Value: imageKey},
		},
	}, nil
}

// handleCallMCPTool routes a tool call to the MCP registry.
func (b *BridgeExecutor) handleCallMCPTool(ctx context.Context, intent *nlrouter.Intent) (*GenericResponse, error) {
	serverID := paramStr(intent.Params, "server_id")
	toolName := paramStr(intent.Params, "tool_name")

	if serverID == "" || toolName == "" {
		return errorResponse(400, "缺少 MCP 参数", "请指定 MCP Server 和工具名称。"), nil
	}

	if b.mcpRegistry == nil {
		return errorResponse(500, "MCP 服务未配置", "MCP_Registry 未初始化。"), nil
	}

	input, _ := intent.Params["input"].(map[string]interface{})
	if input == nil {
		input = make(map[string]interface{})
	}

	result, err := b.mcpRegistry.CallTool(ctx, serverID, toolName, input)
	if err != nil {
		return errorResponse(500, "MCP 工具调用失败",
			fmt.Sprintf("调用 %s.%s 失败: %s\n建议: 请检查 MCP Server 是否在线，或使用 /help 查看帮助。", serverID, toolName, err.Error())), nil
	}

	return &GenericResponse{
		StatusCode: 200,
		StatusIcon: "🔧",
		Title:      "MCP 工具调用成功",
		Body:       fmt.Sprintf("已调用 %s.%s", serverID, toolName),
		Fields: []ResponseField{
			{Label: "结果", Value: fmt.Sprintf("%v", result)},
		},
	}, nil
}

// handleRunSkill executes a registered skill.
func (b *BridgeExecutor) handleRunSkill(ctx context.Context, intent *nlrouter.Intent) (*GenericResponse, error) {
	skillName := paramStr(intent.Params, "skill_name")
	if skillName == "" {
		// If no skill name, list available skills.
		if b.skillExec != nil {
			skills := b.skillExec.List(ctx)
			if len(skills) == 0 {
				return &GenericResponse{
					StatusCode: 200,
					StatusIcon: "ℹ️",
					Title:      "Skill 列表",
					Body:       "暂无已注册的 Skill。",
				}, nil
			}
			fields := make([]ResponseField, 0, len(skills))
			for _, s := range skills {
				fields = append(fields, ResponseField{
					Label: s.Name,
					Value: fmt.Sprintf("%s (触发: %s)", s.Description, strings.Join(s.Triggers, ", ")),
				})
			}
			return &GenericResponse{
				StatusCode: 200,
				StatusIcon: "📦",
				Title:      fmt.Sprintf("可用 Skill (%d 个)", len(skills)),
				Fields:     fields,
			}, nil
		}
		return errorResponse(400, "缺少 Skill 名称", "请指定要执行的 Skill 名称。"), nil
	}

	if b.skillExec == nil {
		return errorResponse(500, "Skill 服务未配置", "Skill_Executor 未初始化。"), nil
	}

	params, _ := intent.Params["params"].(map[string]interface{})
	if params == nil {
		params = make(map[string]interface{})
	}

	var progressMsgs []string
	progressFn := func(step int, msg string) {
		progressMsgs = append(progressMsgs, msg)
	}

	if err := b.skillExec.Execute(ctx, skillName, params, progressFn); err != nil {
		body := fmt.Sprintf("Skill \"%s\" 执行失败: %s", skillName, err.Error())
		if len(progressMsgs) > 0 {
			body += "\n\n执行进度:\n" + strings.Join(progressMsgs, "\n")
		}
		return errorResponse(500, "Skill 执行失败", body), nil
	}

	body := fmt.Sprintf("Skill \"%s\" 执行完成。", skillName)
	if len(progressMsgs) > 0 {
		body += "\n\n执行进度:\n" + strings.Join(progressMsgs, "\n")
	}

	return &GenericResponse{
		StatusCode: 200,
		StatusIcon: "✅",
		Title:      "Skill 执行完成",
		Body:       body,
	}, nil
}

// handleViewMemory displays the user's memory data.
func (b *BridgeExecutor) handleViewMemory(ctx context.Context, userID string) (*GenericResponse, error) {
	if b.memoryStore == nil {
		return errorResponse(500, "记忆服务未配置", "Memory_Store 未初始化。"), nil
	}

	mem, err := b.memoryStore.Get(ctx, userID)
	if err != nil {
		return errorResponse(500, "获取记忆失败", fmt.Sprintf("错误: %s", err.Error())), nil
	}

	fields := []ResponseField{
		{Label: "默认工具", Value: defaultOrNone(mem.DefaultTool)},
		{Label: "记忆条目数", Value: fmt.Sprintf("%d", mem.RecentCount)},
	}

	for k, v := range mem.Preferences {
		fields = append(fields, ResponseField{Label: k, Value: v})
	}

	if len(mem.PatternCounts) > 0 {
		var patterns []string
		for k, v := range mem.PatternCounts {
			patterns = append(patterns, fmt.Sprintf("%s (%d次)", k, v))
		}
		fields = append(fields, ResponseField{
			Label: "操作模式",
			Value: strings.Join(patterns, ", "),
		})
	}

	return &GenericResponse{
		StatusCode: 200,
		StatusIcon: "🧠",
		Title:      "记忆数据",
		Fields:     fields,
		Actions: []ResponseAction{
			{Label: "清除记忆", Command: "清除我的记忆", Style: "danger"},
		},
	}, nil
}

// handleClearMemory clears the user's memory data.
func (b *BridgeExecutor) handleClearMemory(ctx context.Context, userID string) (*GenericResponse, error) {
	if b.memoryStore == nil {
		return errorResponse(500, "记忆服务未配置", "Memory_Store 未初始化。"), nil
	}

	if err := b.memoryStore.Clear(ctx, userID); err != nil {
		return errorResponse(500, "清除记忆失败", fmt.Sprintf("错误: %s", err.Error())), nil
	}

	return &GenericResponse{
		StatusCode: 200,
		StatusIcon: "🗑",
		Title:      "记忆已清除",
		Body:       "您的记忆数据已全部清除，包括偏好设置和操作历史。",
	}, nil
}

// handleCrystallizeSkill triggers skill crystallization from recent context.
func (b *BridgeExecutor) handleCrystallizeSkill(ctx context.Context, userID string) (*GenericResponse, error) {
	if b.crystallizer == nil {
		return errorResponse(500, "技能沉淀服务未配置", "Skill_Crystallizer 未初始化。"), nil
	}

	candidate, err := b.crystallizer.CrystallizeFromContext(ctx, userID)
	if err != nil {
		return errorResponse(500, "技能沉淀失败",
			fmt.Sprintf("无法从最近操作中生成候选 Skill: %s\n建议: 请先执行一些操作，再尝试沉淀。", err.Error())), nil
	}

	return &GenericResponse{
		StatusCode: 200,
		StatusIcon: "💎",
		Title:      "候选 Skill 已生成",
		Body:       fmt.Sprintf("已从最近操作中生成候选 Skill: \"%s\"", candidate.Name),
		Fields: []ResponseField{
			{Label: "名称", Value: candidate.Name},
			{Label: "描述", Value: candidate.Description},
			{Label: "步骤数", Value: fmt.Sprintf("%d", len(candidate.Steps))},
		},
	}, nil
}

// handleHelp returns the help message.
func (b *BridgeExecutor) handleHelp() *GenericResponse {
	return &GenericResponse{
		StatusCode: 200,
		StatusIcon: "📋",
		Title:      "帮助 — 可用操作",
		Body: "您可以使用自然语言或斜杠命令与我交互:\n\n" +
			"• 查看设备 / /machines — 列出所有设备\n" +
			"• 查看会话 / /sessions — 列出所有会话\n" +
			"• 启动会话 — 例如 \"用 Claude 帮我看看项目\"\n" +
			"• 切换会话 / /use <编号> — 进入会话上下文\n" +
			"• 退出会话 / /exit — 退出当前会话\n" +
			"• 截屏 / /screenshot — 获取会话截屏\n" +
			"• 中断会话 / /interrupt — 发送中断信号\n" +
			"• 终止会话 / /kill — 终止会话\n" +
			"• 查看记忆 — 查看偏好和操作历史\n" +
			"• 清除记忆 — 清除所有记忆数据\n" +
			"• 保存为技能 — 将最近操作沉淀为 Skill\n\n" +
			"💡 在会话上下文中，直接发文本即为命令。",
	}
}

// handleUnknown returns a response with 3 most likely intent suggestions.
func (b *BridgeExecutor) handleUnknown(intent *nlrouter.Intent) *GenericResponse {
	body := "我不太确定你想做什么。"

	// Suggest up to 3 candidates if available.
	suggestions := suggestIntents(intent)
	if len(suggestions) > 0 {
		body += "\n\n您是否想要:\n"
		for i, s := range suggestions {
			body += fmt.Sprintf("%d. %s\n", i+1, s)
		}
	}

	body += "\n发送 /help 查看所有可用操作。"

	return &GenericResponse{
		StatusCode: 200,
		StatusIcon: "🤔",
		Title:      "无法理解",
		Body:       body,
		Actions: []ResponseAction{
			{Label: "查看帮助", Command: "/help", Style: "primary"},
		},
	}
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

// resolveSessionID extracts a session ID from intent params, falling back to
// fuzzy matching against the context window and session list.
func (b *BridgeExecutor) resolveSessionID(ctx context.Context, userID string, intent *nlrouter.Intent) string {
	// Direct session_id param.
	if sid := paramStr(intent.Params, "session_id"); sid != "" {
		return sid
	}

	// Fuzzy session reference (e.g. "那个 Claude 会话").
	ref := paramStr(intent.Params, "session_ref")
	if ref != "" {
		return b.fuzzyMatchSession(ctx, userID, ref)
	}

	// Fall back to active session from context window.
	if b.contextMgr != nil {
		cw := b.contextMgr.Get(userID)
		if cw.ActiveSession != "" {
			return cw.ActiveSession
		}
	}

	return ""
}

// fuzzyMatchSession attempts to match a fuzzy session reference (like "那个
// Claude 会话" or "Claude session") against the user's session list and
// context window.
func (b *BridgeExecutor) fuzzyMatchSession(ctx context.Context, userID, ref string) string {
	lower := strings.ToLower(ref)

	// First check context window for active session matching the reference.
	if b.contextMgr != nil {
		cw := b.contextMgr.Get(userID)
		if cw.ActiveSession != "" && cw.ActiveTool != "" {
			if strings.Contains(lower, strings.ToLower(cw.ActiveTool)) {
				return cw.ActiveSession
			}
		}
	}

	// Search through session list for tool name or title match.
	if b.sessions != nil {
		sessions, err := b.sessions.ListSessions(ctx, userID)
		if err == nil {
			var matches []SessionInfo
			for _, s := range sessions {
				if strings.Contains(lower, strings.ToLower(s.Tool)) ||
					strings.Contains(lower, strings.ToLower(s.Title)) ||
					strings.Contains(lower, strings.ToLower(s.ID)) {
					matches = append(matches, s)
				}
			}
			if len(matches) == 1 {
				return matches[0].ID
			}
			// If multiple matches, prefer the most recent (last in list).
			if len(matches) > 0 {
				return matches[len(matches)-1].ID
			}
		}
	}

	return ""
}

// paramStr extracts a string parameter from the intent params map.
func paramStr(params map[string]interface{}, key string) string {
	if params == nil {
		return ""
	}
	v, ok := params[key]
	if !ok {
		return ""
	}
	s, ok := v.(string)
	if !ok {
		return fmt.Sprintf("%v", v)
	}
	return s
}

// errorResponse creates a GenericResponse for error conditions with Chinese
// messages and suggested actions.
func errorResponse(code int, title, body string) *GenericResponse {
	icon := "❌"
	if code == 400 {
		icon = "⚠️"
	} else if code == 404 {
		icon = "🔍"
	}
	return &GenericResponse{
		StatusCode: code,
		StatusIcon: icon,
		Title:      title,
		Body:       body,
	}
}

// defaultOrNone returns the value or "未设置" if empty.
func defaultOrNone(s string) string {
	if s == "" {
		return "未设置"
	}
	return s
}

// intentDescriptions maps intent names to Chinese descriptions for suggestions.
var intentDescriptions = map[string]string{
	nlrouter.IntentListMachines:     "查看设备列表",
	nlrouter.IntentListSessions:     "查看会话列表",
	nlrouter.IntentSessionDetail:    "查看会话详情",
	nlrouter.IntentUseSession:       "切换到某个会话",
	nlrouter.IntentSendInput:        "发送命令到会话",
	nlrouter.IntentInterruptSession: "中断会话",
	nlrouter.IntentKillSession:      "终止会话",
	nlrouter.IntentLaunchSession:    "启动新会话",
	nlrouter.IntentScreenshot:       "获取会话截屏",
	nlrouter.IntentHelp:             "查看帮助",
	nlrouter.IntentExitSession:      "退出当前会话上下文",
	nlrouter.IntentCallMCPTool:      "调用 MCP 工具",
	nlrouter.IntentRunSkill:         "执行 Skill",
	nlrouter.IntentViewMemory:       "查看记忆数据",
	nlrouter.IntentClearMemory:      "清除记忆数据",
	nlrouter.IntentCrystallizeSkill: "将操作沉淀为 Skill",
}

// suggestIntents returns up to 3 intent suggestions based on candidates or
// common intents.
func suggestIntents(intent *nlrouter.Intent) []string {
	var suggestions []string

	// Use candidates from the intent if available.
	if len(intent.Candidates) > 0 {
		for _, c := range intent.Candidates {
			if desc, ok := intentDescriptions[c.Name]; ok {
				suggestions = append(suggestions, desc)
			}
			if len(suggestions) >= 3 {
				break
			}
		}
	}

	// Fill with common intents if we don't have enough.
	defaults := []string{
		nlrouter.IntentListMachines,
		nlrouter.IntentListSessions,
		nlrouter.IntentHelp,
	}
	for _, d := range defaults {
		if len(suggestions) >= 3 {
			break
		}
		desc := intentDescriptions[d]
		// Avoid duplicates.
		dup := false
		for _, s := range suggestions {
			if s == desc {
				dup = true
				break
			}
		}
		if !dup {
			suggestions = append(suggestions, desc)
		}
	}

	return suggestions
}
