version: '3.8'

services:
  dangbei-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dangbei-api
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./config.json:/app/config.json
    environment:
      - TZ=Asia/Shanghai
